global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "konsulent_api"
    metrics_path: /metrics
    static_configs:
      - targets: ["konsulent_api:8000"]

  - job_name: "llm_verktoy_api"
    metrics_path: /metrics
    static_configs:
      - targets: ["llm_verktoy_api:8000"]
